dbtcloud:
  outputs:
    dev:
      account: ZJB65738
      database: analytics
      password: Sachin$123
      role: analyticsengineer
      schema: dbt_atrivedi
      threads: 3
      type: snowflake
      user: sachin
      warehouse: transform_wh
  target: dev



