sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: partsupps
      - name: customers
      - name: suppliers
      - name: regions
      - name: nations
      - name: orders
        config:
          freshness: 
            warn_after: {count: 2, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: o_orderdate::timestamp_ntz
      - name: lineitems
      - name: parts
  - name: src2
    database: mkmotors_dev
    schema: staging
    tables:
        - name: stg_employees